// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNYnF2cqS0evYTgisbVVmrFMJpHWDdvM',
    appId: '1:809810241985:web:9e6cb487dbbfb9cbef2740',
    messagingSenderId: '809810241985',
    projectId: 'kanban-board-10d1b',
    authDomain: 'kanban-board-10d1b.firebaseapp.com',
    storageBucket: 'kanban-board-10d1b.appspot.com',
    measurementId: 'G-HQ4YQ73WME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqRL7jQOuMG8SiAYJlyJq3PF_juxVPICs',
    appId: '1:809810241985:android:30b8e89ced127adeef2740',
    messagingSenderId: '809810241985',
    projectId: 'kanban-board-10d1b',
    storageBucket: 'kanban-board-10d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmYbAqnXjWueD2Tt02rAQmeK02f3N6CsQ',
    appId: '1:809810241985:ios:6c23612365487d5cef2740',
    messagingSenderId: '809810241985',
    projectId: 'kanban-board-10d1b',
    storageBucket: 'kanban-board-10d1b.appspot.com',
    iosClientId: '809810241985-rl06brv40l15kulmr4ukt2fvenfsa7mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmYbAqnXjWueD2Tt02rAQmeK02f3N6CsQ',
    appId: '1:809810241985:ios:6c23612365487d5cef2740',
    messagingSenderId: '809810241985',
    projectId: 'kanban-board-10d1b',
    storageBucket: 'kanban-board-10d1b.appspot.com',
    iosClientId: '809810241985-rl06brv40l15kulmr4ukt2fvenfsa7mg.apps.googleusercontent.com',
    iosBundleId: 'com.example.timeTrackingApp',
  );
}
